# Generated by Django 2.2.6 on 2019-11-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20191127_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
