# Generated by Django 2.2.6 on 2019-12-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_song_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='votes',
        ),
    ]
