# Generated by Django 2.2.6 on 2019-12-25 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_remove_song_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favorites',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
