# Generated by Django 2.2.6 on 2020-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_auto_20191225_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
